# Importing libraries 
import matplotlib.pyplot as plt 
import numpy as np 
  
fig, axs = plt.subplots(2)
fig.suptitle('Eulero')
x, y = np.loadtxt('Eulero.dat', usecols=(2, 0), unpack=True)
v1, v2 = np.loadtxt('Eulero.dat', usecols=(2, 1), unpack=True)
e1, e2 = np.loadtxt('Eulero.dat', usecols=(2, 3), unpack=True)
axs[0].plot(x, y, color='darkslategrey', label='x(t)')
axs[0].plot(v1, v2, color='blue', label='v(t)', linestyle='dashed', alpha=0.2)
axs[0].set(xlabel='$t$', ylabel='$x(t)$')
axs[1].plot(e1, e2, color='skyblue', label='E(t)')
axs[1].set(xlabel='$t$', ylabel='$E(t)$')
for ax in axs.flat:
    ax.legend()
plt.tight_layout() 
plt.savefig('Eulero.pdf')
plt.show() 

fig, axs = plt.subplots(2)
fig.suptitle('Eulero-Cromer')
x, y = np.loadtxt('EuleroCromer.dat', usecols=(2, 0), unpack=True)
v1, v2 = np.loadtxt('EuleroCromer.dat', usecols=(2, 1), unpack=True)
e1, e2 = np.loadtxt('EuleroCromer.dat', usecols=(2, 3), unpack=True)
axs[0].plot(x, y, color='darkslategrey', label='x(t)')
axs[0].plot(v1, v2, color='blue', label='v(t)', linestyle='dashed', alpha=0.2)
axs[0].set(xlabel='$t$', ylabel='$x(t)$')
axs[1].plot(e1, e2, color='skyblue', label='E(t)')
axs[1].set(xlabel='$t$', ylabel='$E(t)$')
for ax in axs.flat:
    ax.legend()
plt.tight_layout() 
plt.savefig('Eulero-Cromer.pdf')
plt.show() 

fig, axs = plt.subplots(2)
fig.suptitle('Mid Point')
x, y = np.loadtxt('MidPoint.dat', usecols=(2, 0), unpack=True)
v1, v2 = np.loadtxt('MidPoint.dat', usecols=(2, 1), unpack=True)
e1, e2 = np.loadtxt('MidPoint.dat', usecols=(2, 3), unpack=True)
axs[0].plot(x, y, color='darkslategrey', label='x(t)')
axs[0].plot(v1, v2, color='blue', label='v(t)', linestyle='dashed', alpha=0.2)
axs[0].set(xlabel='$t$', ylabel='$x(t)$')
axs[1].plot(e1, e2, color='skyblue', label='E(t)')
axs[1].set(xlabel='$t$', ylabel='$E(t)$')
for ax in axs.flat:
    ax.legend()
plt.tight_layout() 
plt.savefig('MidPoint.pdf')
plt.show() 

fig, axs = plt.subplots(2)
fig.suptitle('MidPointImplicito')
x, y = np.loadtxt('MidPointImplicito.dat', usecols=(2, 0), unpack=True)
v1, v2 = np.loadtxt('MidPointImplicito.dat', usecols=(2, 1), unpack=True)
e1, e2 = np.loadtxt('MidPointImplicito.dat', usecols=(2, 3), unpack=True)
axs[0].plot(x, y, color='darkslategrey', label='x(t)')
axs[0].plot(v1, v2, color='blue', label='v(t)', linestyle='dashed', alpha=0.2)
axs[0].set(xlabel='$t$', ylabel='$x(t)$')
axs[1].plot(e1, e2, color='skyblue', label='E(t)')
axs[1].set(xlabel='$t$', ylabel='$E(t)$')
for ax in axs.flat:
    ax.legend()
plt.tight_layout() 
plt.savefig('MidPointImplicito.pdf')
plt.show() 

fig, axs = plt.subplots(2)
fig.suptitle('Confronto tra Metodi per $t=100 s$')
x1, y1 = np.loadtxt('E100.dat', usecols=(2, 0), unpack=True)
xe1, ye1 = np.loadtxt('E100.dat', usecols=(2, 3), unpack=True)
x2, y2 = np.loadtxt('EC100.dat', usecols=(2, 0), unpack=True)
xe2, ye2 = np.loadtxt('EC100.dat', usecols=(2, 3), unpack=True)
x3, y3 = np.loadtxt('MP100.dat', usecols=(2, 0), unpack=True)
xe3, ye3 = np.loadtxt('MP100.dat', usecols=(2, 3), unpack=True)
x4, y4 = np.loadtxt('MPI100.dat', usecols=(2, 0), unpack=True)
xe4, ye4 = np.loadtxt('MPI100.dat', usecols=(2, 3), unpack=True)
axs[0].plot(x1, y1, color='darkslategrey', label='Eulero', alpha=0.3)
axs[0].plot(x2, y2, color='skyblue', label='Eulero-Cromer', alpha=0.3)
axs[0].plot(x3, y3, color='blue', label='MidPoint', alpha=0.3)
axs[0].plot(x4, y4, color='cyan', label='MidPoint Implicito', alpha=0.3)
axs[0].set(xlabel='$t$', ylabel='$x(t)$')
axs[1].plot(xe1, ye1, color='darkslategrey', label='Eulero', alpha=0.3)
axs[1].plot(xe2, ye2, color='skyblue', label='Eulero-Cromer', alpha=0.3)
axs[1].plot(xe3, ye3, color='blue', label='MidPoint', alpha=0.3)
axs[1].plot(xe4, ye4, color='cyan', label='MidPoint Implicito', alpha=0.3)
axs[1].set(xlabel='$t$', ylabel='$E(t)$')
for ax in axs.flat:
    ax.legend()
plt.tight_layout() 
plt.savefig('Confronto.pdf')
plt.show() 

