# Importing libraries
import matplotlib as mat
import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter, FuncFormatter, MultipleLocator
import matplotlib.patches as mpatches
import numpy as np 

plt.figure(figsize=(40,24))
plt.title('Diagramma di Biforcazione al variare di $d\\theta/dt$ e di f0', fontsize=50)
plt.xlabel('$f0$', fontsize=35)
plt.ylabel('$d\\theta/dt$', fontsize=35)
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
xp1, vp1 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK0.dat', usecols=(0, 1), unpack=True)
xp2, vp2 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK1.dat', usecols=(0, 1), unpack=True)
xp3, vp3 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK2.dat', usecols=(0, 1), unpack=True)
xp4, vp4 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK3.dat', usecols=(0, 1), unpack=True)
xp5, vp5 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK4.dat', usecols=(0, 1), unpack=True)
xp6, vp6 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK5.dat', usecols=(0, 1), unpack=True)
xp7, vp7 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK6.dat', usecols=(0, 1), unpack=True)
xp8, vp8 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK7.dat', usecols=(0, 1), unpack=True)
xp9, vp9 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK8.dat', usecols=(0, 1), unpack=True)
xp10, vp10 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK9.dat', usecols=(0, 1), unpack=True)
xp11, vp11 = np.loadtxt('/workspaces/Computazionale/Lab4/File/Biforcazione/BiforcazioneK10.dat', usecols=(0, 1), unpack=True)
plt.scatter(xp1, vp1, color='darkslategrey', marker='.', s=0.1, label='$K=0$')
plt.scatter(xp2, vp2, color='blue', marker='.', s=0.1, label='$K=1$')
plt.scatter(xp3, vp3, color='green', marker='.', s=0.1, label='$K=2$')
plt.scatter(xp4, vp4, color='skyblue', marker='.', s=0.1, label='$K=3$')
plt.scatter(xp5, vp5, color='red', marker='.', s=0.1, label='$K=4$')
plt.scatter(xp6, vp6, color='black', marker='.', s=0.1, label='$K=5$')
plt.scatter(xp7, vp7, color='cyan', marker='.', s=0.1, label='$K=6$')
plt.scatter(xp8, vp8, color='magenta', marker='.', s=0.1, label='$K=7$')
plt.scatter(xp9, vp9, color='purple', marker='.', s=0.1, label='$K=8$')
plt.scatter(xp10, vp10, color='grey', marker='.', s=0.1, label='$K=9$')
plt.scatter(xp11, vp11, color='green', marker='.', s=0.1, label='$K=10$')
patch1 = mpatches.Patch(color='Darkslategrey', label='$\\dot\\theta=0$')
patch2= mpatches.Patch(color='blue', label='$\\dot\\theta=\\pi/10$')
patch3 = mpatches.Patch(color='green', label='$\\dot\\theta=\\pi/5$')
patch4 = mpatches.Patch(color='skyblue', label='$\\dot\\theta=3\\pi/10$')
patch5 = mpatches.Patch(color='red', label='$\\dot\\theta=4\\pi/10$')
patch6 = mpatches.Patch(color='black', label='$\\dot\\theta=\\pi/2$')
patch7 = mpatches.Patch(color='cyan', label='$\\dot\\theta=6\\pi/10$')
patch8 = mpatches.Patch(color='magenta', label='$\\dot\\theta=7\\pi/10$')
patch9 = mpatches.Patch(color='purple', label='$\\dot\\theta=8\\pi/10$')
patch10 = mpatches.Patch(color='grey', label='$\\dot\\theta=9\\pi/10$')
patch11 = mpatches.Patch(color='green', label='$\\dot\\theta=\\pi$')
plt.legend(handles=[patch1, patch2, patch3, patch4, patch5, patch6, patch7, patch8, patch9, patch10, patch11], loc='lower left', fontsize=25)
plt.savefig('/workspaces/Computazionale/Lab4/Grafici/Biforcazione.png')